sudo: false
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
before_script:
  - chmod 777 ./bin/mese
  - chmod 777 ./bin/mese-build
  - chmod 777 ./bin/mese-init
  - chmod 777 ./bin/mese-serve
  - chmod 777 ./bin/mese-test
  - chmod 777 ./bin/mese-watch
install:
  - npm install
after_success:
  - bash <(curl -s https://codecov.io/bash)